version: "3.9"
services:
  energy-backend:
    build: ./energy-backend
    ports:
      - "5000:80"
    environment:
      - Spa__Brand=electron
  energy-spa:
    build: ./energy-spa
    ports:
      - "5050:80"
    links:
      - energy-backend
      