version: "3.9"
networks:
  demo:
services:
  energy-backend:
    deploy:
      replicas: 2
    build: ./energy-backend
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ENV=lab
      - CONSUL__HOST=consul
      - CONSUL__PORT=8500
      - PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.energy-backend.rule=Host(`energy-backend.localhost`)"
      - "traefik.http.routers.energy-backend.entrypoints=web"
    networks:
      - demo
  spa-electron:
    build: ./energy-spa
    links:
      - energy-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.electron.rule=Host(`electron.localhost`)"
      - "traefik.http.routers.electron.entrypoints=web"
    networks:
      - demo
  spa-photon:
    build: ./energy-spa
    links:
      - energy-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photon.rule=Host(`photon.localhost`)"
      - "traefik.http.routers.photon.entrypoints=web"
    networks:
      - demo

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - consul
    networks:
      - demo
  consul:
    image: consul:1.11.4
    hostname: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - demo
